import Foundation
import AppKit
import CryptoKit

/// Generates per-profile `.app` bundle wrappers so each Chrome profile can
/// have its own Dock icon and Cmd+Tab identity. See ARCHITECTURE.md §2.
struct BundleFactory {

    enum FactoryError: LocalizedError {
        case cannotWrite(URL)
        case launcherCompilationFailed
        var errorDescription: String? {
            switch self {
            case .cannotWrite(let url): return "Cannot write to \(url.path())."
            case .launcherCompilationFailed: return "Failed to build the launcher shim."
            }
        }
    }

    /// Where all generated wrappers live.
    static let wrappersRoot: URL = {
        let home = FileManager.default.homeDirectoryForCurrentUser
        return home.appending(path: "Applications/ProfilePilot", directoryHint: .isDirectory)
    }()

    /// Create (or overwrite) a wrapper .app for the given profile. Returns the URL.
    @discardableResult
    func createWrapper(for profile: BrowserProfile, browserExecutableURL: URL) throws -> URL {
        try FileManager.default.createDirectory(at: Self.wrappersRoot,
                                                withIntermediateDirectories: true)

        let appName = wrapperName(for: profile)
        let bundleURL = Self.wrappersRoot.appending(path: "\(appName).app", directoryHint: .isDirectory)

        // 1. Clean any previous version.
        if FileManager.default.fileExists(atPath: bundleURL.path()) {
            try? FileManager.default.removeItem(at: bundleURL)
        }

        // 2. Skeleton.
        let contents = bundleURL.appending(path: "Contents", directoryHint: .isDirectory)
        let macOSDir = contents.appending(path: "MacOS", directoryHint: .isDirectory)
        let resourcesDir = contents.appending(path: "Resources", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: macOSDir, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: resourcesDir, withIntermediateDirectories: true)

        // 3. Info.plist
        let bundleID = wrapperBundleID(for: profile)
        let plist: [String: Any] = [
            "CFBundleDevelopmentRegion": "en",
            "CFBundleDisplayName": appName,
            "CFBundleExecutable": "launcher",
            "CFBundleIdentifier": bundleID,
            "CFBundleInfoDictionaryVersion": "6.0",
            "CFBundleName": appName,
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": "1.0",
            "CFBundleVersion": "1",
            "CFBundleIconFile": "AppIcon",
            "LSMinimumSystemVersion": "14.0",
            "LSApplicationCategoryType": "public.app-category.productivity",
            "LSUIElement": false,
            "LSBackgroundOnly": false,
            "NSHighResolutionCapable": true,
            "NSHumanReadableCopyright": "Generated by ProfilePilot"
        ]
        let plistData = try PropertyListSerialization.data(fromPropertyList: plist,
                                                            format: .xml,
                                                            options: 0)
        try plistData.write(to: contents.appending(path: "Info.plist"))

        // 4. PkgInfo
        try "APPL????".data(using: .ascii)?
            .write(to: contents.appending(path: "PkgInfo"))

        // 5. launcher shim — a bash script that spawns Chrome with the right profile.
        //    We use `open -na` so macOS treats this bundle as the launcher and the
        //    resulting Chrome process gets a fresh NSApplication instance.
        let profileArg = profile.browserKind.profileArgumentName
        let shim = """
        #!/bin/bash
        # Generated by ProfilePilot — launches \(profile.displayName)
        exec /usr/bin/open -na "\(browserExecutableURL.path())" --args \(profileArg)="\(profile.directory)"
        """
        let launcherURL = macOSDir.appending(path: "launcher")
        try shim.write(to: launcherURL, atomically: true, encoding: .utf8)
        _ = try? FileManager.default.setAttributes([.posixPermissions: 0o755],
                                                    ofItemAtPath: launcherURL.path())

        // 6. Icon — stub: copy default AppIcon.icns if we have one bundled.
        if let iconAsset = Bundle.main.url(forResource: "AppIcon", withExtension: "icns") {
            try? FileManager.default.copyItem(at: iconAsset,
                                              to: resourcesDir.appending(path: "AppIcon.icns"))
        }

        // 7. Register with Launch Services so Cmd+Tab / Dock sees it immediately.
        LSRegisterURL(bundleURL as CFURL, true)

        return bundleURL
    }

    // MARK: - Naming

    func wrapperName(for profile: BrowserProfile) -> String {
        let browserShort: String = {
            switch profile.browserKind {
            case .chrome:   return "Chrome"
            case .edge:     return "Edge"
            case .brave:    return "Brave"
            case .chromium: return "Chromium"
            case .arc:      return "Arc"
            case .firefox:  return "Firefox"
            case .safari:   return "Safari"
            }
        }()
        return "\(browserShort) — \(profile.displayName)"
    }

    func wrapperBundleID(for profile: BrowserProfile) -> String {
        let seed = "\(profile.browserBundleID)::\(profile.directory)"
        let hash = SHA256.hash(data: Data(seed.utf8))
        let short = hash.prefix(6).map { String(format: "%02x", $0) }.joined()
        let slug = profile.browserKind.rawValue
        return "com.profilepilot.wrapper.\(slug).\(short)"
    }
}
