#!/usr/bin/env bash
# ============================================================================
# ensure-env-local.sh — idempotently make sure scripts/.env.local exists.
#
# Behaviour:
#   1. If scripts/.env.local already exists → do nothing (never overwrite).
#   2. Else if scripts/.env.local.example exists → copy it.
#   3. Else → write an inline template (so a broken .gitignore or a partial
#      clone can never break `bootstrap.sh`).
#
# Portable: only uses /bin/sh-compatible builtins + `cp`. Runs on Linux + macOS.
# Safe to run any number of times.
#
# Exit codes:
#   0  scripts/.env.local exists at end (whether we made it or not).
#   1  something is broken (parent dir not writable etc.).
# ============================================================================
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${DIR}/.." && pwd)"
ENV_LOCAL="${REPO_ROOT}/scripts/.env.local"
ENV_EXAMPLE="${REPO_ROOT}/scripts/.env.local.example"

log() { printf '  %s\n' "$*"; }

mkdir -p "${REPO_ROOT}/scripts"

if [[ -f "${ENV_LOCAL}" ]]; then
    log "scripts/.env.local already exists — leaving untouched."
    exit 0
fi

if [[ -f "${ENV_EXAMPLE}" ]]; then
    cp "${ENV_EXAMPLE}" "${ENV_LOCAL}"
    log "Created scripts/.env.local from scripts/.env.local.example"
    exit 0
fi

# Fallback: inline template. Kept in one place so it can never drift from the
# example file. Same content — if you edit one, edit the other.
cat > "${ENV_LOCAL}" <<'ENV_TEMPLATE'
# Copy this file to scripts/.env.local (gitignored) and fill in the values
# that are specific to your Apple Developer account. This file is loaded
# automatically by scripts/_env.sh.

# ─── Signing ────────────────────────────────────────────────────────────────
# Run `security find-identity -p codesigning -v` and copy the exact string
# between the quotes for your Developer ID Application certificate.
DEVELOPER_ID_APPLICATION="Developer ID Application: YOUR NAME (TEAMID1234)"
DEVELOPMENT_TEAM="TEAMID1234"

# ─── Notarisation ───────────────────────────────────────────────────────────
# You should store credentials in the keychain ONCE with:
#   xcrun notarytool store-credentials "ProfilePilotNotary" \
#     --apple-id "you@icloud.com" \
#     --team-id "TEAMID1234" \
#     --password "abcd-efgh-ijkl-mnop"   # app-specific pwd from appleid.apple.com
NOTARY_KEYCHAIN_PROFILE="ProfilePilotNotary"

# Only used by CI, not by the local scripts:
APPLE_ID="you@icloud.com"
APPLE_APP_SPECIFIC_PASSWORD="abcd-efgh-ijkl-mnop"

# ─── Sparkle ────────────────────────────────────────────────────────────────
# Public key generated by `Sparkle/bin/generate_keys`. Paste the base64 string
# into Info.plist's SUPublicEDKey too. bootstrap.sh does this for you.
SPARKLE_ED_PUBLIC_KEY=""
APPCAST_URL="https://profilepilot.app/appcast.xml"
ENV_TEMPLATE

log "scripts/.env.local.example was missing — created scripts/.env.local from inline template."
log "Fill in your Apple values before running ./scripts/release.sh."
exit 0
